"""Tabular, model-based teleport-MDP quantities (numpy, no torch)."""

from teleport_mdp.tabular.model_functions import (
    FloatArray,
    compute_d,
    compute_delta,
    compute_expected_model_advantage,
    compute_expected_policy_advantage,
    compute_model_advantage,
    compute_p_tau,
    compute_policy_advantage,
    compute_q_from_u,
    compute_r_s_a,
    compute_relative_model_advantage,
    compute_relative_policy_advantage,
    compute_transition_kernel,
    compute_u_from_v,
    compute_v_from_q,
    get_d_exp_model,
    get_d_exp_policy,
    get_d_inf_model,
    get_d_inf_policy,
    get_policy,
    get_sup_difference,
    softmax_policy,
)
from teleport_mdp.tabular.q_learning import (
    MetricLogger,
    QLearner,
    QLearningResult,
)

__all__ = [
    "FloatArray",
    "MetricLogger",
    "QLearner",
    "QLearningResult",
    "compute_d",
    "compute_delta",
    "compute_expected_model_advantage",
    "compute_expected_policy_advantage",
    "compute_model_advantage",
    "compute_p_tau",
    "compute_policy_advantage",
    "compute_q_from_u",
    "compute_r_s_a",
    "compute_relative_model_advantage",
    "compute_relative_policy_advantage",
    "compute_transition_kernel",
    "compute_u_from_v",
    "compute_v_from_q",
    "get_d_exp_model",
    "get_d_exp_policy",
    "get_d_inf_model",
    "get_d_inf_policy",
    "get_policy",
    "get_sup_difference",
    "softmax_policy",
]
